# homebrew
# https://github.com/Homebrew/homebrew-bundle
brew "tree"
brew "vivid"
brew "tmux"
brew "neovim"
brew "fzf"
brew "bat"
brew "git-delta"
brew "gh"
brew "withgraphite/tap/graphite"
cask "claude-code"
